name: pokemon-hackathon
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - jupyter
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - opencv
  - scikit-learn>=1.0.0
  - pip:
    - ultralytics>=8.0.0
    - transformers>=4.20.0
    - safetensors>=0.3.0
    - wandb>=0.15.0
    - albumentations>=1.3.0
    - seaborn>=0.11.0
    - tqdm>=4.60.0
    - plotly>=5.0.0
    - Pillow-SIMD>=9.0.0